# Generated by Django 5.0.6 on 2024-05-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('chpName', models.CharField(max_length=1000)),
                ('status', models.BooleanField()),
                ('note', models.CharField(max_length=50000)),
            ],
        ),
    ]
