# Generated by Django 5.0.6 on 2024-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapteritem',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
