# Generated by Django 5.0.6 on 2024-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chapteritem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapteritem',
            name='note',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
